<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ContentPipeline.Core\ContentPipeline.Core.csproj" />
    <ProjectReference Include="..\ContentPipeline.Orchestration\ContentPipeline.Orchestration.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
